### ISSUE TITLE
Repeating tracks when playing a Collected Album

### ISSUE THREAD

**Issue by jherskowitz** [tomahawk-player/tomahawk-android#11]
When I play an album I collected, it (sometimes?) plays a couple of songs and then starts the album from the beginning again. So it repeats the first couple of songs but then seems to recover.

**Comment by mrmaffen** [comment]
Does this only happen for collected albums? I'm not sure how to reproduce this :/

**Comment by jherskowitz** [comment]
I'm not sure I can reproduce it now - but encountered it a few times earlier in the week.  I'll keep trying.

**Comment by jherskowitz** [comment]
I just had it happen a bunch more. Play collected album from Collection. Playback order is funky and inconsistent. Repeats tracks, skips tracks. Shuffle and Repeat are both off. Just sent a log.

**Comment by mrmaffen** [comment]
Should be fixed
