### ISSUE TITLE
Tomahawk wants permission to sj

### ISSUE THREAD

**Issue by ViKomprenas** [tomahawk-player/tomahawk-android#12]
No, that isn't a typo in the title. When activating Google Play Music capability it asks for a permission to "sj". That's all it says. It has a Google "g" logo and "sj". Playback works fine, though.

Nexus 9, Android 6.0, Tomahawk latest (downloaded five minutes ago)

**Comment by mrmaffen** [comment]
This is expected behaviour because we use the unofficial Google Music API. Unfortunately we can't change the way Google presents this permission request. "sj" is short for SkyJam (Source: http://dpogue.ca/gmusic.html)
