### ISSUE TITLE
strange message when asking permissions for Google acxount

### ISSUE THREAD

**Issue by pszi1ard** [tomahawk-player/tomahawk-android#23]
When asking for permission to access the Google account information incomplete information is displayed: https://goo.gl/photos/gZYgVrW4LHdHmKaw6

**Comment by mrmaffen** [comment]
Unfortunately this is how Google decides to display the dialog. We can't tell Google to display this in a more complete and detailed way. The service we need permission for is called "sj" (short for SkyJam), which is necessary to get access to the unofficial GMusic API.

**Comment by pszi1ard** [comment]
Thanks for the explanation, I was not aware of this service!
