### ISSUE TITLE
BlurTransformation getting failed because of missing library files

### ISSUE THREAD

**Issue by indiego** [tomahawk-player/tomahawk-android#24]
Running the code on [Moto E](http://www.gsmarena.com/motorola_moto_e-6376.php) crashes the application when BlurTransformation is used to set blurred image to the ImageView.

`E/RenderScript_jni﹕ Error loading RS jni library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.tomahawk.tomahawk_android-2/base.apk"],nativeLibraryDirectories=[/data/app/org.tomahawk.tomahawk_android-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "librsjni.so"`

**Comment by mrmaffen** [comment]
Did you compile Tomahawk for ARMv7a devices? It looks like you compiled it for ARM devices and that's why it can't find the library files.

**Comment by indiego** [comment]
I have installed all the things mentioned in the readme using SDK manager. Can you please tell me where i can find how to compile for ARMv7a devices? I am relatively new to android and was under the impression that the apk pushed to the device is universal and doesn't target any specific architecture.

**Comment by mrmaffen** [comment]
That's a weird bug...
You would normally compile with ./gradlew assembleArmv7aDebug to only compile for armv7a devices. ./gradlew assembleDebug would compile one apk per architecture (arm, armv7a, x86).
Can you test if that also works for you while using build tools 23.0.2? Thanks!

**Comment by mrmaffen** [comment]
@indiego Did you test it yet?

**Comment by indiego** [comment]
@mrmaffen I compiled for both arm and armv7a devices using build tool 23.0.2. It seems the issue is only present in the apk compiled for arm and not armv7a. 

I did the same with build tool 22.0.1 and both arm and armv7a versions work fine.

**Comment by mrmaffen** [comment]
Thanks for getting back to me!
