### ISSUE TITLE
Tomahawk crashes everytime I turn off my screen.

### ISSUE THREAD

**Issue by GAumala** [tomahawk-player/tomahawk-android#27]
I'm using a Huawei P8 Lite with Android 4.4. If I turn off the screen I get this error:

![screenshot from 2016-03-15 22-01-14](https://cloud.githubusercontent.com/assets/5729175/13800734/fb6475c2-eaf9-11e5-8516-7d64a0f64175.png)

**Comment by mrmaffen** [comment]
This should be fixed since https://github.com/tomahawk-player/tomahawk-android/commit/af1348beeb88125a4049d4accbc2fee1c6f19053
Please comment if this crash still happens for you
