### ISSUE TITLE
Support prev/next track through sys API

### ISSUE THREAD

**Issue by michiwend** [tomahawk-player/tomahawk-android#32]
When using a connected Bluetooth device like a car entertainment system I cannot control previous/next track in tomahawk. This also applies for screen gestures on my OnePlus 2.
Albeit play/pause works as expected in both scenarios.

**Comment by mrmaffen** [comment]
Fixed https://github.com/tomahawk-player/tomahawk-android/commit/738698ce5a776bac60a95fd5c9c54aa9ac792233

**Comment by michiwend** [comment]
:thumbsup:
