### ISSUE TITLE
Cannot add Google Play Music Family 

### ISSUE THREAD

**Issue by kgizdov** [tomahawk-player/tomahawk-android#33]
Hi, 

I have a Google Play Music All Access through Family account, but when I try to enable it, the menu that pops to choose an account is empty. 
![screenshot_20160326-012142](https://cloud.githubusercontent.com/assets/3164953/14057229/5f6d4ebe-f2f1-11e5-9167-62533ce497d1.png)

Here's my account type. 
![screenshot_20160326-012243](https://cloud.githubusercontent.com/assets/3164953/14057236/7cd1f8b0-f2f1-11e5-8a5f-ebb6e1de5138.png)

Previously, I had my normal All Access account connected but now it doesn't work. I tried deleting app data and reinstalling, but still nothing.

**Comment by mrmaffen** [comment]
Do you have a Google account stored on your device? Are you using an Android device with or without Google apps like the Play Store app?
Tomahawk should simply list all available Google accounts that it can find.

**Comment by kgizdov** [comment]
@mrmaffen I'm not sure how to be more clear than the screenshots with my Google account in the Play Music app. I have a stock Nexus 6P (non-rooted) with Android 6.0.1 (latest update). All Google Services and apps enabled and I even have two Google accounts on the device. As I mentioned before, it used to work when I had an All Access account, but now I switched to an All Access Family account as it's a better option for me. I'm not sure if that helps, but is the only thing that has changed on my side.

**Comment by mrmaffen** [comment]
You can now login the old fashioned way if there seemingly is no google account present on the device. So this issue should be fixed by https://github.com/tomahawk-player/tomahawk-android/commit/562c1877083d3126b78393d278350e0d6b953872
