### ISSUE TITLE
Tomahawk not playing files opened with filebrowser

### ISSUE THREAD

**Issue by TobBla** [tomahawk-player/tomahawk-android#35]
Using ES File Explorer (pro) to open an mp3 file and choosing Tomahawk for playback will start (or maximize) Tomahawk, but not actually load or play the file.
Choosing one of the other players (Play Music for example) works fine (not a permission issue).

Playing the file from within Tomawak works (not a file issue) :/

HTC one M8
Android 6.0 (H11)

**Comment by mrmaffen** [comment]
Fixed https://github.com/tomahawk-player/tomahawk-android/commit/8af52afe70e9c71c4a7da4521fdfa5b41cd714e2
