### ISSUE TITLE
Amazon Music Internal Error

### ISSUE THREAD

**Issue by icebal** [tomahawk-player/tomahawk-android#36]
trying to add an account to Amazon Music plugin gives the error: Amazon Music: Internal error.
all other plugins i have access to besides Beets work just fine
running on Android 6.0.1 on Nexus 5x

**Comment by icebal** [comment]
adb logcat shows the helpful entry below:
04-11 21:32:04.245  8965  9572 D ScriptResolver: amazon has been disabled

**Comment by tonelowke** [comment]
Also having Amazon Music issues. Can't login to Amazon account even with correct credentials.

**Comment by theli-ua** [comment]
unfortunately it looks like something have changed and Amazon is just not working with tomahawk-android now

there is no fix available

**Comment by theli-ua** [comment]
Does latest nightly fix this for you?

**Comment by mrmaffen** [comment]
Should be fixed in latest nightly. Please re-open if it isn't
