### ISSUE TITLE
Can't sign up for Hatchet//No music shows up

### ISSUE THREAD

**Issue by Krelanis** [tomahawk-player/tomahawk-android#38]
Whenever I try to sign up with Hatchet either through the app or the browser, it always says that the username has been taken or that there has been a connection error, even though my connection is perfectly fine. // I'm assuming you don't have to sign into Hatchet to use the app, but when I go to the collection page, there's absolutely no music even though I'm signed into Spotify and Soundcloud

**Comment by mrmaffen** [comment]
Is this still an issue? Can you now register a Hatchet account? Showing or importing your spotify/soundcloud collection and playlists is currently not implemented. The collection view is currently meant to show your local tracks on your sdcard and artists/albums that you specific added to your Hatchet collection.
