### ISSUE TITLE
Tomahawk Down

### ISSUE THREAD

**Issue by ulamnet** [tomahawk-player/tomahawk-android#40]
![crash](https://cloud.githubusercontent.com/assets/583003/15442877/acbafe7e-1eec-11e6-9c9a-400085348561.png)

I have a one issue here ; tomahawk crash , down.... When ı run this application.

How to fix .? Thanks

**Comment by mrmaffen** [comment]
Hi,
if you just sent the crash report with a terse description of what happened, then that's all we need for now. I have fixed quite a lot of crashes since the last beta release. The next one should bring big improvements in that regard. Stay tuned!
