### ISSUE TITLE
Hatchet does not sync

### ISSUE THREAD

**Issue by kerts93** [tomahawk-player/tomahawk-android#41]
I registered hatched account but my playlist does not sync between my PC and android.

**Comment by kerts93** [comment]
https://github.com/tomahawk-player/tomahawk/issues/517

**Comment by SanKro** [comment]
PC does not sync. Android Sync works (titles and playlist)

**Comment by kerts93** [comment]
Shouldn't they sync to each other also?

**Comment by theli-ua** [comment]
@kerts93 PC version only syncs to hatchet, not from

**Comment by mrmaffen** [comment]
as theli said this issue is not an issue with tomahawk-android. tomahawk-android syncs from and to hatchet, while tomahawk-desktop currently only syncs to hatchet (not from). That's why e.g. playlists you've created on Hatchet or in tomahawk-android don't show up in tomahawk-desktop.
