### ISSUE TITLE
Repeats playing previous song while loading/preparing current one

### ISSUE THREAD

**Issue by theli-ua** [tomahawk-player/tomahawk-android#45]
eg:
A is playing
A have played to the end 
B is being prepared/getStreamUrl-ed  .... at this point Tomahawk is playing A from the start again
Once B is prepared - A stops playing, B starts playing

**Comment by theli-ua** [comment]
This happens only if B is not a direct url and has to go through resolver's getStreamUrl

**Comment by theli-ua** [comment]
I haven't experienced this issue really in a while. Might just be fixed by something

**Comment by mrmaffen** [comment]
Wasn't able to reproduce it in the first place. Please re-open this issue if it happens again and/or you can reproduce it. It'd also be helpful to know to which sources the relevant tracks have been resolved to.

**Comment by theli-ua** [comment]
Just happened to me on master, seem to usually happen when A is from youtube

**Comment by theli-ua** [comment]
Log:  https://www.dropbox.com/s/9dojqs4r6pic8we/tomahawk.log.txt?dl=0

while track "super creature" was preparing it was playing previous youtube track

**Comment by mrmaffen** [comment]
I'm pretty sure this is fixed now. Please re-open if it happens again
