### ISSUE TITLE
Queue restarts

### ISSUE THREAD

**Issue by theli-ua** [tomahawk-player/tomahawk-android#49]
When I play my favorites (~450 tracks) and enable shuffle
It plays several (~5) tracks .... and then just starts over

**Comment by theli-ua** [comment]
So, this happens when you close screen for example.
Looks like a bug when Activity is restored?

**Comment by theli-ua** [comment]
I've recently sent a log with this issue

**Comment by theli-ua** [comment]
So this happens when Playlist.fromCursor is called which calls setCursor which clears cached entries

**Comment by theli-ua** [comment]
^ when that is called from hatchet infoplugin getParseConvert 

(when tomahawk is not currently the front application)

**Comment by mrmaffen** [comment]
should be fixed https://github.com/tomahawk-player/tomahawk-android/commit/362f7aea1f98ca1bf3316e1e0d7b4f56e7de24e5
