### ISSUE TITLE
Use initial query when passing to resolvers

### ISSUE THREAD

**Issue by theli-ua** [tomahawk-player/tomahawk-android#52]
eg Query starts with "Vildhjarta - Traces", gets resolved by YT to "Vildhjarta Traces [HQ/HD]" and is passed like that to following resolver which cant resolve because of that

**Comment by mrmaffen** [comment]
good catch! fixed by https://github.com/tomahawk-player/tomahawk-android/commit/2d0a8a0f52095848ed5ec51b92c129e698b9cddb
