### ISSUE TITLE
Incorrect grouping of songs in albums

### ISSUE THREAD

**Issue by asibs** [tomahawk-player/tomahawk-android#55]
When viewing an album, it incorrectly includes songs from multiple artists because there are multiple artists with different albums which happen to have the same album name.

This is occurring using local music on my Android device.

The specific example is the Album 'No Control' by Bad Religion, the tags for the files in the album are:
Artist: "Bad Religion"
Album artist: (empty)
Album: "No Control"
Year: 1989
Genre: "Alternative & Punk"

However, I have a single song from another artist with album name of 'No Control' which is also getting inserted into this album in the Android app:
Artist: "Pinboys"
Album artist: "Peter Criss"
Album: "No Control"
Year: 2000
Genre: "Miscellaneous"

I suspect that the album artist tag is not being treated correctly - I would expect that if the album artist is not specified, then only songs with the same artist and empty album artist are grouped together eg.

Eg.
All songs with the same album name / album artist / year form an album.
If album artist is empty, then all songs with the same album name / artist / year form an album.

**Comment by asibs** [comment]
I would be happy to look into fixing this issue if someone is able to point me in the right direction within the code base.

**Comment by mrmaffen** [comment]
fixed by https://github.com/tomahawk-player/tomahawk-android/commit/48f89a408851e41fbb88be91bb651b4696900c82
