### ISSUE TITLE
[build-system] read the version from tags

### ISSUE THREAD

**Issue by Avinash-Bhat** [tomahawk-player/tomahawk-android#64]
the apk version name could be easily loaded from git repository itself this is an added advantage for sending out releases as there will not be any need for commits for just changing the version.

As for the apk version code, the same could again be loaded from the git repository itself the build-script for this is available from https://gist.github.com/Avinash-Bhat/12fc59b3d96cb427e5e9 (this may require some tweaking)

I will send a PR so that you can look at this.

**Comment by Avinash-Bhat** [comment]
Note that the above code is based on one of my [stackoverflow answer](http://stackoverflow.com/questions/14895123/auto-version-numbering-your-android-app-using-git-and-eclipse/20584169#20584169) 3 years ago.

**Comment by Avinash-Bhat** [comment]
The PR calculates the version code by parsing the version name, like it is used before the change. so this should also work as intended.

**Comment by mrmaffen** [comment]
Thanks! Your commit has been merged
